# Generated by Django 5.1.5 on 2025-01-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_postpoint_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментарі'},
        ),
    ]
